[tool.poetry]
name = "apextrack-web"
version = "0.1.0"
description = ""
authors = ["Simon Pinfold <simon@uint8.me>"]

[tool.poetry.dependencies]
python = "^3.6"

overtrack-models = { git = "https://gitlab.com/OverTrack/overtrack-models.git", branch = "master" }

dataclasses = "*"

typedload = "*"
zappa = "^0.48"

flask = "^1"
bootstrap-flask = "*"
pyjwt = "*"
requests_oauthlib = "*"
shortuuid = "*"

pynamodb = "^4"

numpy = "*"

google-cloud-logging = "^1"
pytest = "^4.4"
datadog = "^0.29"
sentry_sdk = "^0.11"

stripe = "^2.35"
#certifi = "^2019.6"

[tool.poetry.dev-dependencies]

#pytest = "*"
#pytest-ordering = "*"
#pytest-sugar = "*"
#pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
