[tool.poetry]
name = "apextrack-web-poc"
version = "0.1.0"
description = ""
authors = ["Simon Pinfold <simon@uint8.me>"]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = "*"

typedload = "*"
zappa = "^0.48"

flask = "^1"
bootstrap-flask = "*"
pyjwt = "*"
requests_oauthlib = "*"
shortuuid = "*"

pynamodb = "^3"

numpy = "*"

sentry-sdk = "^0.8"
google-cloud-logging = "^1"
pytest = "^4.4"

[tool.poetry.dev-dependencies]

#pytest = "*"
#pytest-ordering = "*"
#pytest-sugar = "*"
#pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
